### ISSUE TITLE
withdraw new sentences

### ISSUE THREAD

**Issue by Mateandras53** [tbitai/ruzsa#3]
If you begin a new sentence with the button +, you can't withdraw this step in this moment. The only thing you can do is to reload the page and begin again from the beginning.

**Comment by tbitai** [comment]
This feature is added in c966b0f2e84f64e68984c5767c242deec1627b24.

@Mateandras53 please test it you too, and let me know if you find any problems with it. If you don't, you can close the issue :smile:

**Comment by tbitai** [comment]
Actually, there was one issue that came to my mind: if there were closed branches signed as such with a `*`, I cut off their `*` leaves too, which I shouldn't. I fixed this now.
